#!/usr/bin/env python3
"""Offline taskstate Phase 2 rendering tests using temporary state only."""
import json
import os
import shutil
import socket
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.dirname(HERE)
if PKG not in sys.path:
    sys.path.insert(0, PKG)
if HERE not in sys.path:
    sys.path.insert(0, HERE)

import render as render_mod
import taskstate


class RenderTest(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.home = os.path.join(self.tmp.name, "home")
        self.repo = os.path.join(self.tmp.name, "repo")
        os.makedirs(self.home)
        os.makedirs(self.repo)
        self.old_cwd = os.getcwd()
        os.chdir(self.repo)
        self.addCleanup(os.chdir, self.old_cwd)
        self.old_env = {key: os.environ.get(key) for key in (
            "TASKSTATE_HOME", "TASKSTATE_ACTOR", "TASKSTATE_LEASE_SECONDS",
            "PATH", "CLAUDECODE",
        )}
        self.addCleanup(self._restore_env)
        os.environ["TASKSTATE_HOME"] = self.home
        os.environ["TASKSTATE_ACTOR"] = "test:session"
        os.environ["TASKSTATE_LEASE_SECONDS"] = "7200"
        os.environ.pop("CLAUDECODE", None)
        self._git("init", "-q")
        self._git("config", "user.email", "test@example.invalid")
        self._git("config", "user.name", "Taskstate Test")
        Path(self.repo, "f.txt").write_text("one\n", encoding="utf-8")
        self._git("add", "f.txt")
        self._git("commit", "-qm", "initial")

    def _restore_env(self):
        for key, value in self.old_env.items():
            if value is None:
                os.environ.pop(key, None)
            else:
                os.environ[key] = value

    def _git(self, *args):
        subprocess.run(["git"] + list(args), cwd=self.repo, check=True,
                       capture_output=True, timeout=30)

    def require_knap(self):
        binary = shutil.which("knap")
        if not binary:
            self.skipTest("knap 0.6.x is unavailable: executable not found")
        result = subprocess.run([binary, "--version"], capture_output=True,
                                timeout=10, check=False)
        version = result.stdout.decode("utf-8", errors="replace").strip()
        if result.returncode != 0 or not version.startswith("0.6."):
            self.skipTest("knap 0.6.x is unavailable: found %s" % (version or "unknown version"))

    def tcall(self, argv, human=None):
        return taskstate.run(argv, human=human)

    def ok(self, argv, human=None):
        code, payload = self.tcall(argv, human=human)
        self.assertEqual(code, 0, msg=json.dumps(payload, ensure_ascii=False))
        self.assertTrue(payload.get("ok"), msg=json.dumps(payload, ensure_ascii=False))
        return payload["result"]

    def new_project(self, slug):
        self.ok(["project", "init", "--project", slug, "--slug", slug], human=True)
        return slug

    def add_task(self, slug, title="Task", criteria=None):
        argv = ["task", "add", "--project", slug, "--title", title]
        for criterion in criteria or []:
            argv.extend(["--criterion", criterion])
        return self.ok(argv)["ref"]

    def render(self, view, slug, ref=None, extra=None):
        argv = [view]
        if ref is not None:
            argv.append(ref)
        argv.extend(["--project", slug])
        argv.extend(extra or [])
        return render_mod.main(argv)

    def test_1_every_template_validates(self):
        self.require_knap()
        for path in render_mod.TEMPLATE_FILES.values():
            with self.subTest(template=path.name):
                result = subprocess.run(["knap", "validate", str(path)], capture_output=True,
                                        timeout=10, check=False)
                self.assertEqual(result.returncode, 0, msg=result.stderr.decode("utf-8", errors="replace"))

    def test_2_empty_task_renders_all_views_with_missing(self):
        self.require_knap()
        slug = self.new_project("empty")
        ref = self.add_task(slug)
        for view in ("context", "handoff", "task"):
            with self.subTest(view=view):
                code, output = self.render(view, slug, ref)
                self.assertEqual(code, 0, msg=output)
                self.assertTrue(output.startswith("_Generated by taskstate from "))
                model = json.loads(self.render(view, slug, ref, ["--json"])[1])
                self.assertTrue(model["missing"])
                if view in ("context", "handoff"):
                    self.assertIn("handoff", model["missing"])
        code, output = self.render("handoff", slug, ref)
        self.assertEqual(code, 0, msg=output)
        self.assertIn("No handoff recorded — resume from the facts below", output)
        code, output = self.render("attention", slug)
        self.assertEqual(code, 0, msg=output)
        model = json.loads(self.render("attention", slug, extra=["--json"])[1])
        self.assertIn("attention_items", model["missing"])

    def test_3_partial_multiline_unicode_and_atomic_output(self):
        self.require_knap()
        slug = self.new_project("partial")
        ref = self.add_task(slug, "Résumé 🚀", ["AC-1=works α"])
        claim = self.ok(["claim", "--project", slug, ref])
        owner = ["--attempt", claim["attempt_id"], "--epoch", str(claim["epoch"])]
        body = "héllo wörld 🌟\nline-α\nline-β"
        self.ok(["note", "--project", slug, "--task", ref, "--kind", "progress",
                 "--body", body] + owner)
        self.ok(["evidence", "--project", slug, "--task", ref, "--kind", "test",
                 "--result", "pass", "--criteria", "AC-1", "--command", "pytest -q",
                 "--summary", "one passed"] + owner)
        self.ok(["handoff", "--project", slug, "--task", ref, "--next-action", "ship α",
                 "--summary", body, "--risk", "risk 🌟", "--do-not-repeat", "repeat β"] + owner)
        for view in ("context", "handoff", "task"):
            with self.subTest(view=view):
                code, output = self.render(view, slug, ref)
                self.assertEqual(code, 0, msg=output)
                self.assertIn("héllo wörld 🌟", output)
                self.assertIn("> line\\-α", output)
                self.assertIn("Freshness: current", output)
                if view == "context":
                    self.assertIn("> risk 🌟", output)
                    self.assertIn("> repeat β", output)
        destination = Path(self.tmp.name, "artifacts", "taskstate", "out.md")
        code, output = self.render("context", slug, ref, ["--out", str(destination)])
        self.assertEqual(code, 0, msg=output)
        self.assertEqual(output, "")
        self.assertTrue(destination.is_file())
        self.assertIn("Résumé 🚀", destination.read_text(encoding="utf-8"))

    def test_4_oversized_fields_are_truncated_before_knap(self):
        self.require_knap()
        slug = self.new_project("oversize")
        ref = self.add_task(slug)
        claim = self.ok(["claim", "--project", slug, ref])
        self.ok(["note", "--project", slug, "--task", ref, "--kind", "decision",
                 "--body", "L" * 5000, "--attempt", claim["attempt_id"],
                 "--epoch", str(claim["epoch"])])
        code, output = self.render("context", slug, ref, ["--json"])
        self.assertEqual(code, 0, msg=output)
        model = json.loads(output)
        body = model["decisions"]["items"][0]["body"]
        self.assertLessEqual(len(body), 2000)
        self.assertRegex(body, r"…\[truncated \d+ chars\]$")
        self.assertIn("model.decisions.items[0].body", model["truncated"])
        code, markdown = self.render("context", slug, ref)
        self.assertEqual(code, 0, msg=markdown)
        self.assertIn("truncated", markdown)
        huge_ref = self.add_task(slug, "H" * (5 * 1024 * 1024 + 1))
        model = render_mod.validate("context", render_mod.build_read_model("context", slug, huge_ref))
        with patch.object(render_mod, "_run_knap_version"), \
                patch.object(render_mod, "_invoke_knap", return_value="rendered") as invoke:
            code, output = self.render("context", slug, huge_ref)
        self.assertEqual(code, 0, msg=output)
        payload = invoke.call_args.args[2]
        self.assertLess(len(payload), render_mod.MAX_KNAP_BYTES)
        self.assertIn("model.task.title", model["truncated"])

    def test_5_markdown_hostile_input_is_inert(self):
        self.require_knap()
        slug = self.new_project("hostile")
        ref = self.add_task(slug)
        hostile = "```\n# Heading\n<script>alert(1)</script>\na|b\n---\n{{ title }}\n{% if x %}"
        self.ok(["note", "--project", slug, "--task", ref, "--kind", "decision", "--body", hostile])
        code, output = self.render("context", slug, ref)
        self.assertEqual(code, 0, msg=output)
        self.assertFalse(any(line.startswith("# Heading") for line in output.splitlines()))
        self.assertNotIn("<script>", output)
        self.assertIn("\\<script\\>", output)
        self.assertIn("a\\|b", output)
        self.assertFalse(any(line == "---" for line in output.splitlines()))
        visible = output.replace("\\", "")
        self.assertIn("{{ title }}", visible)
        self.assertIn("{% if x %}", visible)

    def test_6_numeric_zero_and_false_display(self):
        self.require_knap()
        slug = self.new_project("display")
        ref = self.add_task(slug)
        code, output = self.render("task", slug, ref)
        self.assertEqual(code, 0, msg=output)
        self.assertIn("- Hold: no", output)
        self.assertIn("- Publish: no", output)
        model = render_mod.validate("attention", render_mod.build_read_model("attention", slug))
        model["source"]["db_seq"] = 0
        model = render_mod.validate("attention", model)
        output = render_mod.render_model("attention", model)
        self.assertIn("at db_seq 0 (", output)
        self.assertNotIn("db_seq none", output)

    def test_7_contract_violation_renders_nothing(self):
        slug = self.new_project("contract")
        ref = self.add_task(slug)
        invalid = render_mod.build_read_model("task", slug, ref)
        del invalid["task"]
        with patch.object(render_mod, "build_read_model", return_value=invalid), \
                patch.object(render_mod, "_invoke_knap") as invoke:
            code, output = render_mod.main(["task", ref, "--project", slug])
        payload = json.loads(output)
        self.assertEqual(code, 2)
        self.assertFalse(payload["ok"])
        self.assertEqual(payload["error"]["code"], "contract_invalid")
        invoke.assert_not_called()

    def test_8_missing_knap_allows_json_fallback(self):
        slug = self.new_project("noknap")
        ref = self.add_task(slug)
        bin_dir = Path(self.tmp.name, "bin-without-knap")
        bin_dir.mkdir()
        (bin_dir / "git").symlink_to(shutil.which("git"))
        os.environ["PATH"] = str(bin_dir)
        code, output = render_mod.main(["context", ref, "--project", slug])
        payload = json.loads(output)
        self.assertEqual(code, 2)
        self.assertEqual(payload["error"]["code"], "knap_missing")
        self.assertIn("--json", payload["error"]["message"])
        code, output = render_mod.main(["context", ref, "--project", slug, "--json"])
        self.assertEqual(code, 0, msg=output)
        self.assertEqual(json.loads(output)["view"], "context")

    def test_9_attention_all_includes_two_projects(self):
        self.require_knap()
        for slug in ("alpha", "beta"):
            self.new_project(slug)
            ref = self.add_task(slug, slug)
            self.ok(["note", "--project", slug, "--task", ref, "--kind", "question",
                     "--body", "question from %s" % slug])
        (Path(self.home) / "broken.db").write_bytes(b"not a sqlite database")
        code, output = render_mod.main(["attention", "--all"])
        self.assertEqual(code, 0, msg=output)
        self.assertIn("Project: alpha", output)
        self.assertIn("Project: beta", output)
        self.assertIn("store\\_error", output)
        model = json.loads(render_mod.main(["attention", "--all", "--json"])[1])
        items = model["items"]["items"]
        projects = {item["project"] for item in items if item["type"] != "store_error"}
        self.assertEqual(projects, {"alpha", "beta"})
        self.assertTrue(any(item["type"] == "store_error" and item["project"] == "broken"
                            for item in items))

    def test_10_agent_docs_output_is_refused(self):
        self.require_knap()
        slug = self.new_project("private")
        ref = self.add_task(slug)
        forbidden = Path(self.tmp.name, ".agents", "docs", "snapshot.md")
        code, output = self.render("context", slug, ref, ["--out", str(forbidden)])
        self.assertEqual(code, 2)
        self.assertEqual(json.loads(output)["error"]["code"], "output_forbidden")
        self.assertFalse(forbidden.exists())

    def test_11_agent_docs_symlink_into_vault_is_refused(self):
        self.require_knap()
        slug = self.new_project("vaultlink")
        ref = self.add_task(slug)
        vault = Path(self.tmp.name, "vault", "project")
        vault.mkdir(parents=True)
        agents = Path(self.tmp.name, "repo2", ".agents")
        agents.mkdir(parents=True)
        (agents / "docs").symlink_to(vault)
        target = agents / "docs" / "snapshot.md"
        code, output = self.render("context", slug, ref, ["--out", str(target)])
        self.assertEqual(code, 2)
        self.assertEqual(json.loads(output)["error"]["code"], "output_forbidden")
        self.assertFalse((vault / "snapshot.md").exists())


if __name__ == "__main__":
    with patch.object(socket.socket, "connect", side_effect=AssertionError("Network forbidden")):
        unittest.main(verbosity=2)
