"""Generates the router skill's command reference straight from the cyclopts
app tree (ADR-0004 -- docstrings are the single source of truth, so this
module never hand-duplicates a command's help text). Walking the tree
generically, rather than importing a hardcoded verb list, is what lets
sibling slices' new verbs show up here the moment they are merged.
"""

from __future__ import annotations

import inspect
from collections.abc import Callable
from pathlib import Path

import cyclopts

Command = tuple[str, Callable[..., object]]

SKILL_TABLE_START = "<!-- BEGIN GENERATED VERB TABLE -->"
SKILL_TABLE_END = "<!-- END GENERATED VERB TABLE -->"


def iter_commands(app: cyclopts.App) -> list[Command]:
    """Walk `app`'s command tree and collect every leaf command, generically.

    Use when generating documentation or running lint checks over every
    registered CLI verb -- this recurses into command groups so a new verb
    (including one added by a sibling slice) is picked up with no edit here.
    Do NOT use when you only need one command's function by name -- index
    the app directly, e.g. `app["read"].default_command`.

    Example output:
        [('neighbors', <function neighbors>), ('read', <function read>)]

    Example invocation:
        from llmos_vault.cli import app
        from llmos_vault.docs import iter_commands
        iter_commands(app)

    Args:
        app: A cyclopts App -- the top-level app or a command group within it.
    """
    commands: list[Command] = []
    for name, sub in app._registered_commands.items():
        if sub._registered_commands:
            commands.extend((f"{name} {child}", func) for child, func in iter_commands(sub))
        elif sub.default_command is not None:
            commands.append((name, sub.default_command))
    return sorted(commands)


def render_verb_table(commands: list[Command]) -> str:
    """Render a one-line-per-verb markdown table from collected commands.

    Use when building the top-of-file summary for `references/commands.md`,
    or the router skill's own verb table -- both show the same one-line
    summaries, taken from each command's docstring first line.
    Do NOT use when you need the full per-command docs, not just the summary
    row -- use `render_reference`, which includes this table plus them.

    Example output:
        '| verb | summary |\\n| --- | --- |\\n| `read` | Print one note... |'

    Example invocation:
        from llmos_vault.cli import app
        from llmos_vault.docs import iter_commands, render_verb_table
        render_verb_table(iter_commands(app))

    Args:
        commands: Commands as returned by `iter_commands`.
    """
    lines = ["| verb | summary |", "| --- | --- |"]
    for name, func in commands:
        doc = inspect.getdoc(func) or ""
        summary = doc.splitlines()[0] if doc else ""
        lines.append(f"| `{name}` | {summary} |")
    return "\n".join(lines)


def render_reference(app: cyclopts.App) -> str:
    """Render the full markdown command reference: the verb table followed
    by each command's complete docstring.

    Use when regenerating the router skill's `references/commands.md` --
    `llmos-vault docs` calls this and writes the result; the staleness test
    calls this and diffs it against the committed file.
    Do NOT use when you only need the verb list, not the rendered markdown
    -- call `iter_commands` directly.

    Example output:
        '# llmos-vault command reference\\n\\n...## `read`\\n\\nPrint one note...'

    Example invocation:
        from llmos_vault.cli import app
        from llmos_vault.docs import render_reference
        render_reference(app)

    Args:
        app: The top-level cyclopts App to document.
    """
    commands = iter_commands(app)
    lines = [
        "# llmos-vault command reference",
        "",
        "Generated by `llmos-vault docs` -- do not hand-edit; regenerate instead.",
        "",
        "## Verbs",
        "",
        render_verb_table(commands),
        "",
    ]
    for name, func in commands:
        lines.append(f"## `{name}`")
        lines.append("")
        lines.append(inspect.getdoc(func) or "")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_skill(skill_text: str, app: cyclopts.App) -> str:
    """Replace the verb table between the skill's generated-table markers,
    leaving the rest of the skill file untouched.

    Use when regenerating the router skill's own verb table so it never
    drifts from the CLI tree -- `llmos-vault docs` calls this on the current
    `SKILL.md` text before writing it back.
    Do NOT use when the skill file has no marker pair yet -- add
    `SKILL_TABLE_START`/`SKILL_TABLE_END` markers around a table first.

    Example output:
        '---\\nname: vault-cli\\n---\\n\\n<!-- BEGIN GENERATED VERB TABLE -->\\n...'

    Example invocation:
        from llmos_vault.cli import app
        from llmos_vault.docs import render_skill
        render_skill(Path("SKILL.md").read_text(), app)

    Args:
        skill_text: Current contents of the skill's SKILL.md file.
        app: The top-level cyclopts App to document.

    Raises:
        ValueError: `skill_text` has no generated-table marker pair.
    """
    if SKILL_TABLE_START not in skill_text or SKILL_TABLE_END not in skill_text:
        raise ValueError(f"skill text has no {SKILL_TABLE_START}/{SKILL_TABLE_END} markers")
    before, rest = skill_text.split(SKILL_TABLE_START, 1)
    _, after = rest.split(SKILL_TABLE_END, 1)
    table = render_verb_table(iter_commands(app))
    return f"{before}{SKILL_TABLE_START}\n{table}\n{SKILL_TABLE_END}{after}"


def write_reference(app: cyclopts.App, reference_path: Path, skill_path: Path) -> None:
    """Regenerate `reference_path` and the verb table in `skill_path` from
    the live command tree.

    Use when a command's docstring changes or a new verb is registered --
    the CLI's `docs` command calls this so both files match the command tree
    before a commit.
    Do NOT use when you only want to preview the output without writing it --
    call `render_reference`/`render_skill` directly.

    Example output:
        None

    Example invocation:
        from pathlib import Path
        from llmos_vault.cli import app
        from llmos_vault.docs import write_reference
        write_reference(app, Path("references/commands.md"), Path("SKILL.md"))

    Args:
        app: The top-level cyclopts App to document.
        reference_path: Path to write the full command reference to.
        skill_path: Path to the router skill's SKILL.md, whose verb table
            gets replaced in place.
    """
    reference_path.parent.mkdir(parents=True, exist_ok=True)
    reference_path.write_text(render_reference(app))
    skill_path.write_text(render_skill(skill_path.read_text(), app))
