#!/usr/bin/env python3
"""Generate a deterministic project-level spec status overview."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any


GENERATED_HEADER = "# Specs Status\n<!-- generated by spec-status.py; do not edit by hand -->\n"
ACTIVE_PHASES = {"plan", "spec", "examples", "implementing", "verifying"}
COMPLETED_PHASES = {"done", "abandoned"}
PHASE_ORDER = {
    "plan": 0,
    "spec": 1,
    "examples": 2,
    "implementing": 3,
    "verifying": 4,
    "done": 5,
    "abandoned": 6,
}
REQUIRED_FIELDS = {"slug", "title", "phase", "blocked", "updated", "summary", "prs"}


class StatusEntry:
    def __init__(self, metadata: dict[str, Any], path: Path) -> None:
        self.path = path
        self.slug = str(metadata["slug"])
        self.title = str(metadata["title"])
        self.phase = str(metadata["phase"])
        self.blocked = bool(metadata["blocked"])
        self.updated = str(metadata["updated"])
        self.summary = str(metadata["summary"])
        self.issues = list_value(metadata.get("issues", []))
        self.prs = list_value(metadata["prs"])


class StatusProblem:
    def __init__(self, slug: str, problem: str) -> None:
        self.slug = slug
        self.problem = problem


def list_value(value: Any) -> list[str]:
    if value is None:
        return []
    if isinstance(value, list):
        return [str(item) for item in value]
    return [str(value)]


def parse_scalar(value: str) -> Any:
    value = value.strip()
    if value == "[]":
        return []
    if value.startswith("[") and value.endswith("]"):
        inner = value[1:-1].strip()
        if not inner:
            return []
        return [parse_scalar(part.strip()) for part in inner.split(",")]
    if value.lower() == "true":
        return True
    if value.lower() == "false":
        return False
    if (value.startswith('"') and value.endswith('"')) or (
        value.startswith("'") and value.endswith("'")
    ):
        return value[1:-1]
    return value


def parse_frontmatter(text: str) -> dict[str, Any]:
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        raise ValueError("missing frontmatter")

    try:
        end = next(index for index, line in enumerate(lines[1:], start=1) if line.strip() == "---")
    except StopIteration as exc:
        raise ValueError("unterminated frontmatter") from exc

    data: dict[str, Any] = {}
    current_list_key: str | None = None
    for line in lines[1:end]:
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped.startswith("- "):
            if current_list_key is None:
                raise ValueError("list item without key")
            data[current_list_key].append(parse_scalar(stripped[2:]))
            continue
        if ":" not in line:
            raise ValueError(f"invalid frontmatter line: {line}")
        key, raw_value = line.split(":", 1)
        key = key.strip()
        if not key:
            raise ValueError("empty frontmatter key")
        raw_value = raw_value.strip()
        if raw_value:
            data[key] = parse_scalar(raw_value)
            current_list_key = None
        else:
            data[key] = []
            current_list_key = key

    return data


def parse_status(path: Path) -> StatusEntry:
    metadata = parse_frontmatter(path.read_text(encoding="utf-8"))
    missing = sorted(REQUIRED_FIELDS - set(metadata))
    if missing:
        raise ValueError(f"missing required field(s): {', '.join(missing)}")
    if str(metadata["phase"]) not in ACTIVE_PHASES | COMPLETED_PHASES:
        raise ValueError(f"unknown phase: {metadata['phase']}")
    return StatusEntry(metadata, path)


def discover_statuses(specs_dir: Path) -> tuple[list[StatusEntry], list[StatusProblem]]:
    if not specs_dir.is_dir():
        return [], []

    entries: list[StatusEntry] = []
    problems: list[StatusProblem] = []
    for child in sorted(specs_dir.iterdir(), key=lambda item: item.name):
        if not child.is_dir():
            continue
        status_path = child / "STATUS.md"
        if not status_path.exists():
            problems.append(StatusProblem(child.name, "missing STATUS.md"))
            continue
        try:
            entries.append(parse_status(status_path))
        except ValueError as exc:
            problems.append(StatusProblem(child.name, f"malformed STATUS.md frontmatter: {exc}"))

    return entries, problems


def markdown_cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ").strip()


def render_table(headers: list[str], rows: list[list[str]]) -> str:
    if not rows:
        return "_None._\n"
    header = "| " + " | ".join(headers) + " |"
    separator = "| " + " | ".join("---" for _ in headers) + " |"
    body = ["| " + " | ".join(markdown_cell(cell) for cell in row) + " |" for row in rows]
    return "\n".join([header, separator, *body]) + "\n"


def sort_active(entry: StatusEntry) -> tuple[int, bool, str, str]:
    return (PHASE_ORDER.get(entry.phase, 99), entry.blocked, reverse_date(entry.updated), entry.slug)


def sort_completed(entry: StatusEntry) -> tuple[str, str]:
    return (reverse_date(entry.updated), entry.slug)


def reverse_date(value: str) -> str:
    return "".join(chr(255 - ord(char)) for char in value)


def render_overview(entries: list[StatusEntry], problems: list[StatusProblem]) -> str:
    active = sorted(
        [entry for entry in entries if entry.phase not in COMPLETED_PHASES],
        key=sort_active,
    )
    completed = sorted(
        [entry for entry in entries if entry.phase in COMPLETED_PHASES],
        key=sort_completed,
    )
    problem_rows = [[problem.slug, problem.problem] for problem in sorted(problems, key=lambda item: item.slug)]

    parts = [
        GENERATED_HEADER,
        "\n## Active\n\n",
        render_table(
            ["Spec", "Phase", "Blocked", "Updated", "Summary"],
            [
                [
                    entry.slug,
                    entry.phase,
                    "yes" if entry.blocked else "no",
                    entry.updated,
                    entry.summary,
                ]
                for entry in active
            ],
        ),
        "\n## Completed\n\n",
        render_table(
            ["Spec", "Updated", "Summary", "PRs"],
            [
                [
                    entry.slug,
                    entry.updated,
                    entry.summary,
                    ", ".join(entry.prs),
                ]
                for entry in completed
            ],
        ),
    ]
    if problem_rows:
        parts.extend(
            [
                "\n## Needs Attention\n\n",
                render_table(["Spec", "Problem"], problem_rows),
            ]
        )

    return "".join(parts)


def generate_overview(specs_dir: Path | str = Path("specs")) -> str:
    specs_path = Path(specs_dir)
    if not specs_path.is_dir():
        return ""
    entries, problems = discover_statuses(specs_path)
    return render_overview(entries, problems)


def write_overview(specs_dir: Path | str = Path("specs")) -> bool:
    specs_path = Path(specs_dir)
    overview = generate_overview(specs_path)
    if not overview:
        return False
    (specs_path / "STATUS.md").write_text(overview, encoding="utf-8")
    return True


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--specs-dir", default="specs", help="Path to the specs directory.")
    parser.add_argument("--write", action="store_true", help="Write specs/STATUS.md instead of printing.")
    parser.add_argument("--quiet", action="store_true", help="Suppress non-error output.")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    specs_dir = Path(args.specs_dir)

    if args.write:
        wrote = write_overview(specs_dir)
        if wrote and not args.quiet:
            print(f"Wrote {specs_dir / 'STATUS.md'}")
        return 0

    overview = generate_overview(specs_dir)
    if overview:
        print(overview, end="")
    elif not args.quiet:
        print(f"No specs directory found at {specs_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
